feat: #39260 - Add comp. ResourceClassesWithFormik
perfarm/ui-kit pull request #18
Opened 2023-03-23 14:05 UTC by joseafs-seedz

- Add variant Text in Button component;
- Add comp. ResourceTextField;
- Add comp. ResourceClasses;
- Add no-restricted-imports, to avoid parent imports;
- Add isLoading prop in Select;
- Increment error palette;
- Add backgroundTextByColor to reuse by utils;
- Add role to disable select option when active;
- Add json-server for api mocks with db.json;
- Add config/urls, for endpoints and global params;
- Fix theme.spaces, for sequences of 4;

2023-03-29 20:13 UTC, ivanguimam requested changes

2023-03-30 17:49 UTC, joseafs-seedz commented on src/components/ResourceClasses/formik.tsx
> +const FormObserver: React.FC = () => {
arquivo removido, estrutura completa dentro de /stories.tsx

2023-03-30 18:09 UTC, joseafs-seedz commented on src/components/ResourceClasses/index.tsx
> +    if (listByWetDryMatter.length > 0) {
> ```ts
> if (!!listByWetDryMatter.length) {
>   setWetDryMatterFieldVisible(true);
>   return;
> }
> ```

eslint acusou como redundante, então: if (listByWetDryMatter.length) {

2023-03-30 20:00 UTC, ivanguimam requested changes

2023-03-30 20:00 UTC, ivanguimam commented on src/services/api/resourceClasses/fetch/index.ts
> +export const fetch: () => Promise<ResourceClass[]> = async () => {
Cara, ao invés de definir aquim podemos definir na linha 10 que é melhor e fica mais clean

```ts
export const fetch = async () => {
  try {
    const { data } = await api.get<ResourceClass[]>('/resourceClasses');
```

2023-04-03 13:26 UTC, ivanguimam requested changes

2023-04-03 13:26 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +    await waitFor(async () => {
Esse `async` não é necessário, não é obrigatório a função ser uma Promise

```ts
await waitFor(() => {
  fireEvent.click(screen.getByText(options[2].name));
});
```

2023-04-03 13:26 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +    await waitFor(async () => {
Esse `async` não é necessário, não é obrigatório a função ser uma Promise

```ts
await waitFor(() => {
  fireEvent.click(removeButtons[0]);
});
```

2023-04-03 13:26 UTC, ivanguimam commented on tsconfig.json
Cara, faz algumas modificações pra gente melhorar o build e a integração do vscode com o typescript

Alterar o `include` para ficar assim
```json
"include": [
  "scripts/**/*",
  "mocks/**/*",
  ".storybook/**/*",
  "src/**/*"
]
```

Adiciona isso antes do `paths`, que ai o vscode vai conseguir autocompletar os imports

```json
"baseUrl": ".",
```

No `tsconfig.build.json`, deixa o `exclude` assim
```json
  "exclude": [
    "scripts",
    ".storybook/**/*",
    "mocks/**/*",
    "src/**/stories.tsx",
    "src/**/test.tsx"
  ]
```

2023-04-03 18:46 UTC, ivanguimam requested changes

2023-04-03 18:46 UTC, ivanguimam commented on .storybook/templates/ApiMock/index.tsx
> +const mockAdapter = new MockAdapter(api);
Esse mock não pode ficar aqui por conta daquele mesmo problema com o storybook

```tsx
export const ApiMock: FC<Props> = ({ children, onMock }) => {
  const [loading, setLoading] = useState(true);
  const [mock] = useState<MockAdapter>(new MockAdapter(api));

  useDidMount(() => {
    onMock(mock);
    setLoading(false);
  });

  useWillUnmount(() => {
    mock.restore();
  });

  return loading ? <div>loading</div> : <Fragment>{children}</Fragment>;
};
```

2023-04-03 18:46 UTC, ivanguimam commented on .storybook/templates/ApiMock/test.tsx
> +    expect.assertions(2);
Não é necessário já que você não tem nenhum `expect` dentro de um `catch` ou dentro de um `callback`

2023-04-03 18:46 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +  mock.onGet('/resourceClasses').reply(200, options);
Cara, se você fizer assim, você precisa retornar esse `mock` para poder resetar ele no fim de cada teste

2023-04-03 18:46 UTC, ivanguimam commented on src/services/api/resourceClasses/fetch/test.ts
> +    expect(data).toMatchObject(options);
Resetar o mock

2023-04-03 19:56 UTC, ivanguimam requested changes

2023-04-03 19:56 UTC, ivanguimam commented on .storybook/templates/ApiMock/test.tsx
> +    const spy = jest.spyOn(api, 'get');
Remover mock no fim do teste

```ts
spy.mockRestore();
```

2023-04-03 19:56 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +    const mock = new MockAdapter(api);
Cara, como você mocou a função `fetch` nesse teste, não tem pq mocar a api, ela nunca vai ser chamada

2023-04-03 19:56 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +    const mock = new MockAdapter(api);
Cara, como você mocou a função `fetch` nesse teste, não tem pq mocar a api, ela nunca vai ser chamada

2023-04-03 19:56 UTC, ivanguimam commented on src/components/ResourceClasses/test.tsx
> +    const mock = new MockAdapter(api);
Cara, como você mocou a função `fetch` nesse teste, não tem pq mocar a api, ela nunca vai ser chamada

2023-04-04 11:20 UTC, ivanguimam approved these changes

2023-04-04 11:23 UTC, merged