feat: #42527 - Add CropChronogramsTable
perfarm/ui-kit pull request #21
Opened 2023-04-25 13:52 UTC by joseafs-seedz

[feat: #42527 - Add CropChronogramsTable]

[feat: #42527 - Add CropChronogramsTable Total Column]
 
[fix: #42527 - Add tooltipDescription in IndicatorCell]

[feat: #45527 - Tests of CropChronogramsTable]

[feat: #42527 - Add Tooltip description]

2023-04-25 14:02 UTC, joseafs-seedz commented
Próximos passos (fazendo):
- Ajuste nos components/icons para puxar cores do theme, no futuro será ajustado para viewBox quadrado para melhorar o padrão;

2023-04-26 13:44 UTC, henriquece commented on src/components/CropChronogramsTable/index.tsx
> +      header: (<DateGroupColumnHeader>{groupColumn.name}</DateGroupColumnHeader>) as unknown as ColumnDefTemplate<
Nesse header, tá faltando o negrito e deixar só a primeira letra maiúscula.

2023-04-26 13:52 UTC, henriquece commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/mock.ts
> +    name: '(+) Receita de vendas de Bovinos de Corte',
O sinal referente ao fator ("+", "-" ou "=") é depois do texto.

2023-04-27 12:54 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/mock.ts
> +    name: '(+) Receita de vendas de Bovinos de Corte',
Hoje isso é bagunçado, alguns ta do lado direito, outros no esquerdo, mas agora vamos padronizar isso e colocar tudo na esquerda

2023-05-02 17:05 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DateGroupColumnSubheader/index.tsx
> +import { MdInfoOutline } from 'react-icons/md';
Padronizar esse import vir da style ?

2023-05-02 17:13 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/IndicatorCell/index.tsx
> +import { MdInfoOutline } from 'react-icons/md';
Padronizar esse import vir da style ?

2023-05-04 13:59 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/test.tsx
> +    fireEvent.mouseEnter(cellValue);
Não foi possível validar o mouseEnter/Leave com spyOn, e com o getComputedStyles o Stitches não retorna os estilos inseridos no componente, aparentemente é um bug existente.

Link com issue do bug de estilo no stitches: https://github.com/stitchesjs/stitches/issues/874

2023-05-05 19:06 UTC, ivanguimam requested changes

2023-05-05 19:06 UTC, ivanguimam commented on src/utils/sum/index.ts
> +export const sumNumbers = (numbers: number[]) => {
```ts
export const sumNumbers = (numbers: number[]) => numbers.reduce((prev, cur) => isNaN(cur) ? prev : prev + cur, 0);
```

2023-05-10 20:42 UTC, ivanguimam requested changes

2023-05-11 18:21 UTC, ivanguimam approved these changes

2023-05-11 18:21 UTC, merged