feat: #42528 - Add FilterTable component
perfarm/ui-kit pull request #23
Opened 2023-05-15 15:10 UTC by joseafs-seedz

2023-06-07 15:16 UTC, henriquece commented
Substituir "FilterTable" por "TableFilter"

2023-06-07 15:18 UTC, henriquece commented on src/components/FilterTable/style.ts
> +  width: '100%',
No meu teste, esse width tá gerando um scroll horizontal. Talvez, removê-lo.

2023-06-07 15:41 UTC, deyvison-costa approved these changes

2023-06-08 20:51 UTC, ivanguimam requested changes

2023-06-08 20:51 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DataRow/index.tsx
> +        const cellContext = cell.getValue() as CellContextValue;
```ts
const cellContext = cell.getValue<CellContextValue>();
```

2023-06-08 20:51 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DataRow/index.tsx
> +                  <>
* Cara, acho que rola colocar isso em outro componente, para ficar mais organizado
* Como você chama `cell.getContext()` varias vezes, compensa colocar em uma variável

src/components/CropChronogramsTable/components/DataRow/components/OtherComponent/index.ts
```tsx
const OtherComponent: FC<Props> = ({ cellContext, row }) => (
  <Fragment>
    <div className="cell-default">
      {row.original?.prefix} {formatCurrency(cellContext.value)} {row.original?.suffix}
      {cellContext.extra?.value > 0 && (
        <Extra>
          {formatCurrency(cellContext.extra.value)} {row.original?.extra?.suffix}
        </Extra>
      )}
    </div>
    <div className="cell-unity">
      {row.original?.prefix} {formatCurrency(cellContext.valueByUnit)} {row.original?.suffix}
      {cellContext.extra?.value > 0 && (
        <Extra>
          {formatCurrency(cellContext.extra.valueByUnit)} {row.original?.extra?.suffix}
        </Extra>
      )}
    </div>
  </Fragment>
);
```

```tsx
{cell.getContext().getValue() === 'cell-indicator'
  ? flexRender(cell.column.columnDef.cell, cell.getContext())
  : flexRender(<OtherComponent cellContext={cellContext} row={row} />, cell.getContext())}
```

2023-06-08 20:51 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DateGroupColumnHeaderIndicator/type.ts
> +import { PropsWithChildren } from 'react';
```ts
import { MouseEventHandler, PropsWithChildren } from 'react';

type OnwProps = {
  onClickExpand: MouseEventHandler<HTMLButtonElement>;
  onClickRecall: MouseEventHandler<HTMLButtonElement>;
}

export type Props = PropsWithChildren & OnwProps;
```

2023-06-08 20:51 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/HeaderRow/index.tsx
> +  const thClassName = rowIndex > 0 ? 'td' : '';
* Pq o `th` tem uma classe que chama `td`?
* O que acha de colocar em um useMemo?

2023-06-08 20:51 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DataRow/index.tsx
> +    classLineTr = `${lineType} ${row.original?.isFirstLevel ? '' : lineSubType}`;
* Cara acho que pra facilitar a leitura ficaria legal assim:

```ts
const lineType = 'activity-control';
const lineSubType = row.original?.type === 'sub_kind_activity' ? 'activity' : 'resource';
const subType = row.original?.isFirstLevel ? '' : lineSubType; // PENSAR EM UM NOME MELHOR

classLineTr = `${lineType} ${subType}`;
```

2023-06-08 20:51 UTC, ivanguimam commented on src/components/TableFilter/type.ts
> +  onChange: (e: Option<string>) => void;
* Colocar em um tipo

```ts
export type OnChange = (e: Option<string>) => void;

export interface Control {
  maxWidth?: string;
  name: string;
  onChange: OnChange;
```

2023-06-08 20:51 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramInfoById/type.ts
> +  group: 'CROP' | 'PRODUCT' | 'BUSINESS_UNIT' | 'PROPERTY';
* Colocar em um tipo

```ts
export type Group = 'CROP' | 'PRODUCT' | 'BUSINESS_UNIT' | 'PROPERTY';

export interface CropChronogramInfo {
  columns: CropChronogramColumn[];
  enableDivision: boolean;
  group: Group;
```

2023-06-09 17:55 UTC, ivanguimam requested changes

2023-06-09 17:55 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DataRow/components/Cell/types.ts
> +  index?: number;
Acho que podemos remover esse `index`, não ta sendo utilizado

2023-06-09 17:55 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/types.ts
> +  TOTAL?: ColumnValues;
Pq essa chave ta em maiúsculo?

2023-06-09 19:50 UTC, ivanguimam approved these changes

2023-06-09 19:51 UTC, merged