feat: #47774 - Add Status in CropChronogramsTable
perfarm/ui-kit pull request #33
Opened 2023-06-13 16:18 UTC by joseafs-seedz

# Título

#47774 - Adaptar tabela para os 3 status

## Motivação

- Tabela pode ter cenários onde nenhum valor existe, portando dependerá do campo 'status';

<details><summary>Details</summary>
<p>

# blank
  - Não existe tabela
  - Não exibir nada
  - Exibir loader
  - columns será vázio
 
# pending
 - Está em processo de atualização
  - Exibir loader
  - columns com dados
    - Exibir dados antigos
  - columns vázio
    - Pode ou não ter produção
    
# done
  - columns vazio
    - Sem produção
  - columns com dados
    - Exibir dados

</p>
</details> 

## Solução proposta

![image](https://github.com/perfarm/ui-kit/assets/124299550/d74be4f9-f503-4c06-958a-9871562ac7a0)

## Informações adicionais

- Storybook com os três possíveis estados;
- Status 'pending' será refatorado junto com existência do botão para atualizar a DRE;

- [47774](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_workitems/edit/47774/)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [ ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-06-14 20:50 UTC, ivanguimam requested changes

2023-06-14 20:50 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/index.tsx
> +import { TrEmptyLine } from '~/components/CropChronogramsTable/components/TableStructured/components/TrEmptyLine';
```ts
import { TrEmptyLine } from './components/TrEmptyLine';
```

2023-06-15 13:03 UTC, ivanguimam requested changes

2023-06-15 13:03 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/index.tsx
> +                isEmptyLineActive = true;
Pra que esse `isEmptyLineActive = true` bem aqui?

2023-06-15 13:28 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/TableStructured/index.tsx
> +                isEmptyLineActive = true;
É para evitar que quando uma linha divisória for inserida, não exista nenhuma outra além dela, mesmo que o objeto tenha um 'emptyLineBefore'

2023-06-15 16:52 UTC, ivanguimam approved these changes

2023-06-15 16:53 UTC, merged