feat: #50318 - Add Typography component
perfarm/ui-kit pull request #62
Opened 2023-07-04 13:12 UTC by joseafs-seedz

#50318 - Componente de Tipografia

## Motivação

- Muitos campos de texto acabam se repetindo em estrutura e estilo;

## Solução proposta

- Componente de Tipografia para agrupar textos e padrões do figma;

![image](https://github.com/perfarm/ui-kit/assets/124299550/925d2df1-e6f5-4ce1-888a-d10444647ba6)

## Informações adicionais

- variants display por seu tamanho, se encaixam na definição tag 'h1';

- [50318](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_workitems/edit/50318)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-07-04 13:55 UTC, deyvison-costa approved these changes

2023-07-04 13:57 UTC, deyvison-costa approved these changes

2023-07-04 13:57 UTC, deyvison-costa approved these changes

2023-07-04 14:17 UTC, henriquece commented on src/components/CropChronogramsTable/components/DialogInfo/components/UpdateInProgress/style.ts
> +import { Typography } from '~/components/Typography';
Pq importar e exportar nesse arquivo ao invés de importar diretamente de '~/components/Typography' no arquivo "index.tsx"?

2023-07-04 14:18 UTC, henriquece commented on src/components/CropChronogramsTable/components/DialogInfo/components/UpdateNeedWait/style.ts
> +import { Typography } from '~/components/Typography';
Pq importar e exportar nesse arquivo ao invés de importar diretamente de '~/components/Typography' no arquivo "index.tsx"?

2023-07-05 12:46 UTC, henriquece approved these changes

2023-07-05 12:55 UTC, ivanguimam requested changes

2023-07-05 12:55 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DialogInfo/components/UpdateInProgress/index.tsx
>        <div>
Colocar essa `div` no `style.ts`

2023-07-05 12:55 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DialogInfo/components/UpdateInProgress/index.tsx
>          <strong> nova atualização. </strong>
Colocar esse `strong` no `style.ts`

2023-07-05 12:55 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DialogInfo/components/UpdateNeedWait/index.tsx
>          Espere <strong>1 minuto</strong> e tente novamente
Colocar esse `strong` no `style.ts`

2023-07-05 12:55 UTC, ivanguimam commented on src/components/DatePicker/style.ts
> +    {
Pq isso foi pra baixo?

2023-07-05 12:55 UTC, ivanguimam commented on src/components/Typography/test.tsx
> +  test('should show childrenText', () => {
Você consegue fazer um teste que se você passar a tag h1 ele criou o html com a tag h1?

2023-07-05 13:12 UTC, joseafs-seedz commented on src/components/DatePicker/style.ts
> +    {
Pulou por ter chego no limite da  linha mesmo:
[Gravação de tela de 05-07-2023 10:11:50.webm](https://github.com/perfarm/ui-kit/assets/124299550/4594956f-b26b-4d6a-a41b-a309735a007c)

2023-07-07 12:03 UTC, ivanguimam approved these changes

2023-07-07 12:03 UTC, merged