Feature/49973/header drawer
perfarm/ui-kit pull request #79
Opened 2023-07-26 17:32 UTC by deyvison-costa

# Título
### Exibir cabeçalho no drawer para obrigações

## Motivação
Exibir informações do cabeçalho do drawer para melhor experiência do usuário

## Solução proposta
Foi criado um cabeçalho no componente Drawer para orientar o usuário sobre a ação clicada.

## Informações adicionais

[49973 - Exibir cabeçalho no drawer para obrigações](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/DRE%20e%20FC%20V3/D2F%20-%20Perfarm/Sprint%201?workitem=49973)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-07-28 14:04 UTC, henriquece commented on src/components/Icons/Cattle/style.ts
> +export const Root = styled('svg');
A gente tá importando do arquivo "~/commons/variants/svgIcon".

Substituir por:
`export { Path, Root } from '~/commons/variants/svgIcon';`

2023-07-28 14:05 UTC, henriquece commented on src/components/Icons/Cattle/test.tsx
> +describe('ArrowUp', () => {
Trocar "ArrowUp" por "Cattle".

2023-07-28 14:25 UTC, henriquece commented on src/components/TableCellDrawer/Heading/index.tsx
> +      } catch (e) {}
Adicionar "onError", que vem como prop do componente "Table".

2023-07-28 14:49 UTC, henriquece commented on src/components/TableCellDrawer/Heading/generateFakeId/index.ts
> +export const generateFakeId = () => {
Não entendi essa função. Lá no arquivo "stories", deixei um comentário com outra abordagem pra resolver essa questão do "id".

2023-07-28 14:50 UTC, henriquece commented on src/services/api/headingDrawer/fetchFinancialTransaction/mock.ts
> +  name: 'Transação financeira',
Acho que substituir esse "Transação financeira" por algo como "Venda de bezerras" ficaria melhor.

2023-07-28 14:57 UTC, henriquece commented on src/components/Table/stories.tsx
> +      mock.onGet(`/cost-centers/${fakeId()}/info`).reply(HttpStatusCode.Ok, financialTransaction);
Acredito que substituir "\`/cost-centers/${fakeId()}/info\`" pela regex "/\\/cost-centers\\/.*\\/info/" consiga capturar todas as requests.

2023-07-31 18:57 UTC, deyvison-costa commented on src/services/api/headingDrawer/fetchFinancialTransaction/mock.ts
> +  name: 'Transação financeira',
Esse title "Venda de bezerras" deve aparecer no header do drawer de atividades.

2023-08-03 18:07 UTC, ivanguimam requested changes

2023-08-03 18:07 UTC, ivanguimam commented on src/services/api/headingDrawer/fetchFinancialTransaction/index.ts
- FinancialTransaction na verdade é costCenter, pois esse endpoint é para buscar as infos de um centro de custo
- Esse é um endpoint geral da plataforma (não é específico de uma única funcionalidade), por isso é melhor que ele fique num escopo mais geral dentro de api e não dentro de uma funcionalidade específica

`src/services/api/headingDrawer/fetchFinancialTransaction/index.ts` => `src/services/api/costCenter/fetch/index.ts`

2023-08-03 18:07 UTC, ivanguimam commented on src/services/api/headingDrawer/fetchFinancialTransaction/index.ts
> +export const fetchFinancialTransaction = async (id: number | string) => {
* `fetchFinancialTransaction` => `fetchInfo`
* `id` é somente do tipo `number` para centros de custo

2023-08-03 18:07 UTC, ivanguimam commented on src/services/api/headingDrawer/fetchFinancialTransaction/test.ts
> +describe('headingDrawer fetchFinancialTransaction', () => {
fetchInfo

2023-08-03 18:07 UTC, ivanguimam commented on src/services/api/headingDrawer/fetchFinancialTransaction/type.ts
> +export interface FinancialTransaction {
Podemos chamar de `CostCenter` pois é exatamente isso que ele é

2023-08-03 18:07 UTC, ivanguimam commented on src/services/api/headingDrawer/fetchFinancialTransaction/type.ts
> +export type Factor = '+' | '-' | '=';
Acho que podemos achar um lugar mais global para esse `Factor` pois ele é utilizado em vários lugares (DRE, FC) e agora no Drawer

2023-08-03 18:07 UTC, ivanguimam commented on src/components/TableCellDrawer/Heading/index.tsx
> +  const [transactionData, setTransactionData] = useState<FinancialTransaction>({} as FinancialTransaction);
Chamar `transactionData` de `costCenter`

2023-08-08 14:46 UTC, ivanguimam commented on src/components/TableCellDrawer/Heading/index.tsx
> +  useDidMount(() => {
1. Precisamos colcoar um `loader`
2. Pq não fazer assim?
```ts
useDidMount(async () => {
  try {
    const data = await fetchInfo(id);
    setCostCenter(data);
  } catch (e) {
    onError(requestMessages.error);
  }
});
```

2023-08-24 20:34 UTC, ivanguimam requested changes

2023-08-24 20:34 UTC, ivanguimam commented on src/components/TableCellDrawer/Heading/types.ts
> +  id: number;
Se esse componente for utilziado somente para centro de custo, ok essa propriedade for chamada `id`. Agora se esse componente for utilizado no caso de atividades tbm, é melhor chamar essa props de `costCenterId`

2023-08-24 20:49 UTC, ivanguimam approved these changes

2023-08-24 20:51 UTC, merged