Add TableCellDrawer on CropChronograms table
perfarm/ui-kit pull request #80
Opened 2023-07-27 19:58 UTC by henriquece

# Título

Implementar drawer na direita

- [Card no Azure](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/DRE%20e%20FC%20V3/D2F%20-%20Perfarm/Sprint%201?workitem=49980)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-07-31 12:29 UTC, ivanguimam requested changes

2023-07-31 19:43 UTC, henriquece commented on src/components/CropChronogramsTable/components/IndicatorCell/index.tsx
> +              businessUnitId={0}
Não foquei nessas props, pq isso é da task de listagem de atividade/obrigações desse drawer.

2023-07-31 19:44 UTC, henriquece commented on src/components/CropChronogramsTable/components/IndicatorCell/index.tsx
> +              costCenterId={0}
Não foquei nessas props, pq isso é da task de listagem de atividade/obrigações desse drawer.

2023-07-31 19:44 UTC, henriquece commented on src/components/TableCellDrawer/types.ts
> +  onCardClick: OnCardClick;
Pq seria genérico. Seria um "onClick" em que parte do drawer?

2023-07-31 19:52 UTC, henriquece commented on src/components/CropChronogramsTable/components/TableStructured/test.tsx
> +        onActivityClick={() => null}
Seria "garantir que ao clicar na atividade/obrigação"?

2023-08-01 14:33 UTC, ivanguimam approved these changes

2023-08-01 14:33 UTC, merged