Feat/51936
perfarm/ui-kit pull request #81
Opened 2023-07-28 12:29 UTC by joseafs-seedz

# Título

51936 - Implementar limitador de colunas na tabela DRE

## Motivação

- Tabela de DRE apresenta bugs e quebra de memória do navegador quando mais de 60 colunas são abertas.

## Solução proposta

-  Inserido componente Drawer para controlar quais colunas podem ser visualizadas;
- Coluna total é fixa;
[Gravação de tela de 28-07-2023 09:28:01.webm](https://github.com/perfarm/ui-kit/assets/124299550/56505b41-74e5-438d-bc39-a8c1dd8ea54e)

- [51936](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_workitems/edit/51936)

## Checklist:

- [ ] Meu código segue os padrões definidos no projeto
- [ ] Realizei uma autorrevisão do meu código
- [ ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [ ] Testes de unidade novos e existentes passam localmente com minhas alterações
- [ ] Meus componentes possuem storybook

2023-07-31 15:34 UTC, henriquece commented on src/components/CropChronogramsTable/components/TableStructured/index.tsx
> +    if (columnsListActive.length) {
Adicionar optional chaining.

2023-08-01 14:11 UTC, henriquece commented on src/components/CropChronogramsTable/index.tsx
> +const TableStructured = lazy(() => import('./components/TableStructured'));
Acredito que não faça diferença nesse caso, já que o problema de performance é na renderização desse mesmo componente.

2023-08-04 13:30 UTC, ivanguimam requested changes

2023-08-04 13:30 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/style.ts
> +  maxHeight: '100vh',
Pq disso? No storybook pelo menos ta fazendo ficar com 2 scrolls
<img width="272" alt="Screenshot 2023-08-04 at 10 21 40" src="https://github.com/perfarm/ui-kit/assets/24425745/e1463d3b-e2d7-4b39-a74d-6de4383931de">

2023-08-04 13:30 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/types.ts
> +  onDidMount?: () => void;
Colocar em um `type`

2023-08-04 13:30 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/TableStructured/utils.tsx
> +export const createGroupSubColumns: Column<ColumnValues>[] = [
Não seria `createSubGroupColumns`?

2023-08-04 13:30 UTC, ivanguimam commented on src/components/CropChronogramsTable/index.tsx
> +export const CropChronogramsTable: FC<Props> = ({ cellsMaxToShow = 18000, id, onError, onSuccess, tableHeight }) => {
Que isso aqui? Pq desse `18000`??

2023-08-04 13:30 UTC, ivanguimam commented on src/components/CropChronogramsTable/utils/countIndicators/index.ts
> +    for (const item of arr) {
Da pra substituir isso por um `reduce`

2023-08-04 13:30 UTC, ivanguimam commented on src/components/Icons/ArrowSquareOut/style.ts
> +import { Path, Root } from '~/commons/variants/svgIcon';
Pode exportar direto

```ts
export { Path, Root } from '~/commons/variants/svgIcon';
```

2023-08-04 13:30 UTC, ivanguimam commented on src/components/Icons/CaretRight/style.ts
> +import { Path, Root } from '~/commons/variants/svgIcon';
Pode exportar direto

```ts
export { Path, Root } from '~/commons/variants/svgIcon';
```

2023-08-04 13:30 UTC, ivanguimam commented on src/components/Icons/Cattle/style.ts
> +import { Path, Root } from '~/commons/variants/svgIcon';
Pode exportar direto

```ts
export { Path, Root } from '~/commons/variants/svgIcon';
```

2023-08-04 13:30 UTC, ivanguimam commented on src/components/Icons/Table/style.ts
> +import { Path, Root } from '~/commons/variants/svgIcon';
Pode exportar direto

```ts
export { Path, Root } from '~/commons/variants/svgIcon';
```

2023-08-04 13:30 UTC, ivanguimam commented on src/components/Switch/index.tsx
> +      <SwitchRoot checked={checked} disabled={disabled} id={id} isChecked={checked} onCheckedChange={onChange}>
Qual a diferença do `checked` para o `isChecked`? Pq não usar a propriedade `checked` na variant?

2023-08-04 14:43 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/Header/style.ts
> +export const Span = styled('span', {
Por herança, ele já considera o Typography utilizado no <Title> e então repassa pros elementos de texto, com o span

2023-08-04 14:48 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/style.ts
> +  fontFamily: '$montserrat',
O componente drawer possuí uma fontFamily default, então sobrescrevi para a montserrat
![image](https://github.com/perfarm/ui-kit/assets/124299550/4bd941de-0f51-418f-8e00-dc57acc83ab7)

2023-08-04 15:01 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/style.ts
> +  height: 'calc(100% - 189px)',
Esse é para o espaço da área de scroll dos itens da lista limitado a linha horizontal
[Gravação de tela de 04-08-2023 11:56:23.webm](https://github.com/perfarm/ui-kit/assets/124299550/807aebf3-60d4-4d7c-b051-17fdb746b94d)

no caso irei reajustar pra 185 por conta do ajuste no ButtonIcon, mas a pedido do SIlvio que ele foi mantido assim, para dar a sensação que a listagem termina exatamente na linha

2023-08-04 16:41 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/TableStructured/style.ts
> +  maxHeight: '100vh',
Retornei pro modo que estava antes, ambos tem o mesmo comportamento;

- Para evitar esse scroll no storybook o calculo foi reajustado no getTableWrapperCss para quando não vier o **tableHeight**

2023-08-04 16:45 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/index.tsx
> +export const CropChronogramsTable: FC<Props> = ({ cellsMaxToShow = 18000, id, onError, onSuccess, tableHeight }) => {
É numero ideal de células a exibir na tabela

2023-08-04 18:29 UTC, ivanguimam requested changes

2023-08-04 18:29 UTC, ivanguimam commented on src/components/ButtonIcon/style.ts
> +        height: 'unset',
Isso realmente é necessário já que você colocou na ilnha [10](https://github.com/perfarm/ui-kit/pull/81/files#diff-c30678fe707baf19426a78d745193d02655269f191b474254433970d7e16806eR10)???

**Obs:** O mesmo questionamento se aplica aos outras variante do size?

2023-08-04 18:29 UTC, ivanguimam commented on src/components/ButtonIcon/test.tsx
> +    const element = container.getElementsByClassName(className)[0];
```ts
const [icon] = container.getElementsByClassName(className);
```

2023-08-04 18:29 UTC, ivanguimam commented on src/components/ButtonIcon/test.tsx
> +    const element = container.getElementsByClassName(className)[0];
```ts
const [icon] = container.getElementsByClassName(className);
```

2023-08-04 18:29 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/Header/style.ts
> +export const Span = styled('span', {
Eu entendi, meu questionamento é pq não definir a tag `span` no `Typography`? Assim todo e qualquer texto que fossemos inserir a gente sempre usário o `Typography`. E se teria alguma vantagem definir o `span` lá.

2023-08-04 18:29 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/style.ts
> +  fontFamily: '$montserrat',
Entendi, e não rola fazer isso direto o `~/components/Drawer`??? Já que todo nosso sistema usa `montserrat`

2023-08-04 18:29 UTC, ivanguimam commented on src/components/CropChronogramsTable/index.tsx
> +export const CropChronogramsTable: FC<Props> = ({ cellsMaxToShow = 18000, id, onError, onSuccess, tableHeight }) => {
E você isso pra que? Pra limitar oq?

2023-08-04 18:29 UTC, ivanguimam commented on src/components/CropChronogramsTable/utils/countIndicators/index.ts
> +    if (item?.aggregates) {
Só faz sentido tenar percorrer `aggregates` se tiver algum: `item.aggregates?.length`

2023-08-04 18:31 UTC, ivanguimam requested changes

2023-08-04 18:31 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/style.ts
> +  height: 'calc(100% - 189px)',
Entendi, você pode colocar um `padding bottom` interno então de uns `15px`, pq quando chega no últiimo item ele fica grudado na linha

2023-08-04 18:39 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DrawerFilterColumns/Header/style.ts
> +export const Span = styled('span', {
Opa, o span já está definido como possibilidade de uso nas tags do Typography

`export type HtmlTextTags = 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'div' | 'p' | 'span' | 'strong';`

2023-08-07 13:47 UTC, merged