feat: add list on CropChronograms' TableCellDrawer
perfarm/ui-kit pull request #82
Opened 2023-08-04 18:06 UTC by henriquece

# Título

Exibir listagem no drawer para atividades

- [Card no Azure](https://dev.azure.com/Seedz/D2F%20-%20Perfarm/_sprints/taskboard/DRE%20e%20FC%20V3/D2F%20-%20Perfarm/Sprint%202?workitem=49982)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-08-07 14:21 UTC, ivanguimam requested changes

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/Card/index.tsx
> +const SuppliesIcon = lazy(() => import('~/components/Icons/Supplies'));
Realmente tem alguma vantagem a gente utilizar `lazy loading` aqui?

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/Card/index.tsx
> +  const cost = type === 'activities' ? (info as Activity).cost.value : (info as Movement).totalCost;
Compensa colocar essa linha `57` e `58` em um `useMemo`

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +  const indicatorKey = row?.original?.indicatorKey;
Pa não utilizar destructuring?

```tsx
const { cropProductId, id, indicatorId, indicatorKey, resourceType } = row.original;
```

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +      } else if (indicatorKey === 'Receitas de produção') {
Essa `key` ta certa? todas as keys que eu me lembre são nesse padrão `product_external_revenue`

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +      if (table === 'cash-flow') {
Pensar melhor em todo esse `if else` pra ficar mais organizado. As vezes esse `TableCellDrawer` só recebe como parâmetro se é pra ele buscar `movements`, `activities` ou `expenses` e quem implementar ele que se vire, não sei, mas dar uma pensada melhor nesse tanto de `if else`. Tipo, as vezes esse componente recebe esse `type`, sei lá

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +      } else if (indicatorKey === 'Custos de produção') {
Essa `key` ta certa? todas as keys que eu me lembre são nesse padrão `product_external_revenue`

2023-08-07 14:21 UTC, ivanguimam commented on src/components/TableCellDrawer/style.ts
> +export const Cards = styled('div');
Não seria melhor chamar esse componente de `ListRoot` ou algo do tipo?

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/index.ts
> +  sale?: 'INTERNAL' | 'EXTERNAL' | 'ALL';
Podemos definir um `type` para esse `sale` e `buy`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/index.ts
> +export interface FetchParams {
Colocar essa interface em um arquivo `type`: `src/services/api/activities/fetch/type.ts`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/index.ts
> +export const fetch = async ({
Cara, ao invés de fazer esse destructuring no objeto, podemos só repassar ele como `params`

```ts
export const fetch = async (params: FetchParams) => {
  try {
    const { data } = await api.get<Activities>('/activities-consolidators', { params });

    return data;
  } catch (e) {
    if ((e as AxiosError).response) {
      throw RequestError.buildFromAxiosError(e as AxiosError);
    }

    throw e;
  }
};
```

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  cost: {
Cria um `type` pra `Cost`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  hoursmeter: {
Cria um `type` pra `HoursMeter`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  parent?: {
Cria um `type` pra `Parent`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  resources: {
Cria um `type` pra `Resource`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  previsionStatus: 'planned' | 'realized';
Cria um `type` pra `PrevisionStatus`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/activities/fetch/type.ts
> +  icon: string;
Cria um type para esse `icon`, você já sabe quais podem ser

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/type.ts
> +  resourceType?: 'machines' | 'other_resources' | 'supplies' | 'buildings' | 'peoples';
O mesmo resource dessa [linha](https://github.com/perfarm/ui-kit/pull/82/files#diff-20f77ab5cd14978f8c55d617bb51fc2adec906aa90ab520c9295877f5e23ff17R18) serve aqui, no caso todos no plural.

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/type.ts
> +  buy?: 'INTERNAL' | 'EXTERNAL';
Podemos definir um `type` para esse `sale` e `buy`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/type.ts
> +  specificCase?: 'commercialization' | 'buy';
Criar `type` pra isso

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/movements/fetch/index.ts
> +export interface FetchParams {
Colocar interface em um arquivo `type`: `src/services/api/movements/fetch/type.ts`

2023-08-07 14:21 UTC, ivanguimam commented on src/services/api/movements/fetch/index.ts
> +export const fetch = async ({
Fazer algo semelhante ao comentário dessa [linha](https://github.com/perfarm/ui-kit/pull/82/files#diff-20f77ab5cd14978f8c55d617bb51fc2adec906aa90ab520c9295877f5e23ff17R28)

2023-08-08 13:02 UTC, henriquece commented on src/components/TableCellDrawer/index.tsx
> +  const indicatorKey = row?.original?.indicatorKey;
Pq estou utilizando o operador optional chaining.

2023-08-08 13:10 UTC, henriquece commented on src/components/TableCellDrawer/index.tsx
> +      } else if (indicatorKey === 'Receitas de produção') {
![Screenshot from 2023-08-08 10-10-06](https://github.com/perfarm/ui-kit/assets/35502036/f3b4cef7-3ba8-4390-8f1b-55dd66711c8d)

2023-08-08 14:59 UTC, ivanguimam requested changes

2023-08-08 14:59 UTC, ivanguimam commented on src/components/TableCellDrawer/Card/index.tsx
> +  const formattedTotalCost = useMemo(() => formatCurrency(cost, true, true), [cost]);
Na verdade, o `cost` ele pode ficar aqui dentro, já que ele só é utilizado aqui mesmo, ai esse cost da linha `59` não seria necessário

```ts
const formattedCost = useMemo(() => {
  const cost = type === 'activities' ? (info as Activity).cost.value : (info as Movement).totalCost;
  return formatCurrency(cost, true, true);
}, [cost, info, type]);
```

2023-08-08 14:59 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +  const indicatorKey = row?.original?.indicatorKey;
Então, mas é necessário ele no atributo `original`? Pode acontecer de `row.original` ser undefined?

2023-08-08 14:59 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +      } else if (indicatorKey === 'Receitas de produção') {
Procura o Falcão fazendo favor, acho que isso pode ta errado, mostra esse print pra ele

2023-08-08 14:59 UTC, ivanguimam commented on src/components/TableCellDrawer/index.tsx
> +      } else if (indicatorKey === 'Custos de produção') {
Procura o Falcão fazendo favor, acho que isso pode ta errado, mostra esse print pra ele

2023-08-08 14:59 UTC, ivanguimam commented on src/components/TableCellDrawer/types.ts
> +  table: 'crop-chronograms' | 'cash-flow';
Pq desse `table`?

2023-08-08 14:59 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/type.ts
> +  resourceType?: 'machines' | 'other_resources' | 'supplies' | 'buildings' | 'peoples';
Podemos colocar isso em um `type` geral, pois isso vai ser utiliado vária vezes, as vezes omitindo algum valor

2023-08-08 14:59 UTC, ivanguimam commented on src/services/api/cropChronograms/fetchChronogramIndicatorsById/type.ts
> +type Buy = 'INTERNAL' | 'EXTERNAL';
* Podemos colocar isso em um `type` geral, pois isso vai ser utiliado vária vezes, as vezes omitindo algum valor, como no [arquivo](https://github.com/perfarm/ui-kit/pull/82/files#diff-62987fb62b6ddcf79923ed0bf4ce931175807b3e449b7fd80e57c7ef178de6dd)
* `sale` e `buy` seram sempre os mesmo valores, logo podem ter o um tipo só

2023-08-08 17:21 UTC, henriquece commented on src/components/TableCellDrawer/types.ts
> +  table: 'crop-chronograms' | 'cash-flow';
![Screenshot from 2023-08-08 14-21-15](https://github.com/perfarm/ui-kit/assets/35502036/8857b98f-fa12-437a-a722-b945d61c8a47)

2023-08-08 17:27 UTC, henriquece commented
Sobre as keys "Receitas de produção" e "Custos de produção", procurei o Falcão e ele falou que está certo.

2023-08-08 18:34 UTC, ivanguimam requested changes

2023-08-08 18:34 UTC, ivanguimam commented on src/components/TableCellDrawer/types.ts
> +  table: 'crop-chronograms' | 'cash-flow';
Certo, mas realmente tem a necessidade de informar a tabela para o componente `src/components/TableCellDrawer/index.tsx`?? Acho que seria mais simples a gente só informar pra ele se ele vai listar `movements` ou `activities`, assim até mesmo ele ficar mais simples

2023-08-10 12:55 UTC, merged