wip: refactor of update modal with fech status
perfarm/ui-kit pull request #85
Opened 2023-08-14 14:15 UTC by joseafs-seedz

## Motivação

Bug ao abrir modal, quando uma atualização está acontecendo, que foi ativada em outra aba.

## Solução proposta

Ao abrir o modal de atualizar, acontecerá um fetch para coletar o status e o tempo da ultima atualização iniciada;

## Checklist:

- [ ] Meu código segue os padrões definidos no projeto
- [ ] Realizei uma autorrevisão do meu código
- [ ] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [ ] Testes de unidade novos e existentes passam localmente com minhas alterações
- [ ] Meus componentes possuem storybook

2023-08-22 18:47 UTC, henriquece commented on src/components/CropChronogramsTable/stories.tsx
> +      // mock.onGet(`/crop-chronograms/${args.id}/status`).replyOnce(HttpStatusCode.Ok, statusPending);
Excluir esses "mock.onGet" comentados?

2023-08-22 18:54 UTC, henriquece approved these changes

2023-08-24 14:40 UTC, ivanguimam requested changes

2023-08-24 14:40 UTC, ivanguimam commented on src/components/CropChronogramsTable/components/DialogInfo/index.tsx
> +    fetchChronogramStatusById(id)
Aqui estamos usando `then catch` por conta daquele problema no sistema da Perfarm?
Se **sim**, não precisa do `async` na linha `32`
Se **não**, usar `async await` aqui

2023-08-24 14:53 UTC, joseafs-seedz commented on src/components/CropChronogramsTable/components/DialogInfo/index.tsx
> +    fetchChronogramStatusById(id)
sim

2023-08-24 14:55 UTC, ivanguimam approved these changes

2023-08-24 15:06 UTC, merged