Feature/49974/show balance in drawer
perfarm/ui-kit pull request #96
Opened 2023-09-20 15:18 UTC by deyvison-costa

# Título

### 55180 - Exibir total de custo no drawer DRE

## Motivação

Informar o total de custos ao usuário

## Solução proposta

Foi inserido junto ao drawer um bloco com a informação do total de custos do item clicado

## Informações adicionais

[55180 - Exibir total de custo no drawer DRE](https://dev.azure.com/Seedz/D2F%20-%20DirectToFarmer/_sprints/taskboard/Perfarm/D2F%20-%20DirectToFarmer/Sprint%2003?System.AssignedTo=deyvison.costa%40seedz.ag&workitem=55180)

## Checklist:

- [x] Meu código segue os padrões definidos no projeto
- [x] Realizei uma autorrevisão do meu código
- [x] Adicionei testes que provam que minha correção é eficaz ou que meu recurso funciona
- [x] Testes de unidade novos e existentes passam localmente com minhas alterações
- [x] Meus componentes possuem storybook

2023-09-20 16:59 UTC, ivanguimam requested changes

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ActivitiesDrawer/index.tsx
> +import { fetchActivitiesTotalCost } from '~/services/api/costCenter';
Faz mais sentido ficar em `src/services/api/activities` pq o custo das atividades não tem nada haver com `costCenter`

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ActivitiesDrawer/index.tsx
>      if (resourceType && resourceId) {
Isso aqui tbm deve ser colocado nos filters, para ser usado tanto no totalizador como na listagem

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ActivitiesDrawer/index.tsx
> +  const fetchActivitiesTotalCostData = useCallback(async () => {
Podemos renomear isso para `fetchTotalCost` pois já se encontra em um contexto de atividade, não precisa ficar repetindo toda hora, até mesmo o método `fetchActivitiesData` poderia ser renomeado para `fetchList` que não seria um problema

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ActivitiesDrawer/index.tsx
> +      onError('Erro ao buscar suas atividades');
Melhorar mensagem de erro, algo como `Erro ao buscar o valor total das atividades`

2023-09-20 16:59 UTC, ivanguimam commented on src/components/CropChronogramsTable/stories.tsx
> +      mock.onGet(`/movements/total`).reply(HttpStatusCode.Ok, totalCost);
* Colocar delay
* Essa rota na verdade é `/movements/total-value`

2023-09-20 16:59 UTC, ivanguimam commented on src/components/CropChronogramsTable/stories.tsx
> +      mock.onGet(`/activity-consolidators/total-value`).reply(HttpStatusCode.Ok, totalCost);
Colocar delay

2023-09-20 16:59 UTC, ivanguimam commented on src/components/DrawerBodyTable/components/TotalCost/style.ts
> +  backgroundColor: '$gray100',
Cara, esses cores com número no nome é coisa antiga, o certo é utilizar algumas dessas cores:

```
      darkGray: '#494949',
      gray: '#898989',
      lighterGray: '#F9F9F9',
      lightGray: '#EEEEEE',
      mediumGray: '#C4C4C4',

      pastureGreen: '#4BB066',
      pastureGreenDark: '#38844C',
      pastureGreenHover: '#449F5C',
      pastureGreenLight: '#D2EBD8',
      pastureGreenLighter: '#E4F3E8',
      pastureGreenWhitened: '#F6FBF7',

      warningRedAlert: '#F34E4E',
      warningRedDark: '#B63A3A',
      warningRedHover: '#DB4646',
      warningRedLight: '#FCD2D2',
      warningRedLighter: '#FDE5E5',
      warningRedWhitened: '#FEF6F6',

      resourceYellow: '#FFCC00',
      resourceYellowDark: '#DFA300',
      resourceYellowHover: '#EFB700',
      resourceYellowLight: '#FFF2BF',
      resourceYellowLighter: '#FFF8D9',
      resourceYellowWhitened: '#FFFDF2',
```

2023-09-20 16:59 UTC, ivanguimam commented on src/components/DrawerBodyTable/types.ts
> +  totalCost?: number;
Cara, pelo que entendi esse parâmetro é obrigatório, afinal em todo drawer ele é exibido

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ExpenseDrawer/index.tsx
> +      onError('Erro ao buscar suas obrigações');
Melhorar mensagem de erro, semelhante ao de atividades

2023-09-20 16:59 UTC, ivanguimam commented on src/components/ExpenseDrawer/index.tsx
> +  const fetchExpensesTotalCostData = useCallback(async () => {
Podemos renomear isso para `fetchTotalCost` pois já se encontra em um contexto de expenses, não precisa ficar repetindo toda hora, até mesmo o método `fetchExpensesData` poderia ser renomeado para fetchList que não seria um problema

2023-09-20 16:59 UTC, ivanguimam commented on src/components/MovementsDrawer/index.tsx
> +  const fetchMovementsTotalCostData = useCallback(async () => {
Podemos renomear isso para `fetchTotalCost` pois já se encontra em um contexto de movements, não precisa ficar repetindo toda hora, até mesmo o método `fetchMovementsData ` poderia ser renomeado para fetchList que não seria um problema

2023-09-20 16:59 UTC, ivanguimam commented on src/components/MovementsDrawer/index.tsx
> +      onError('Erro ao buscar as informações do centro de custo');
Melhorar mensagem de erro

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchInfo/index.ts
> +export const fetchInfo = async (id: string | number) => {
Isso é sempre um número

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchTotalCost/fetchActivitiesTotalCost/index.tsx
* Faz mais sentido ficar em `src/services/api/activities` pq o custo das atividades não tem nada haver com `costCenter`
* Renomear somente para `fetchTotalCost`

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchTotalCost/fetchExpensesTotalCost/index.tsx
* Faz mais sentido ficar em `src/services/api/expenses` pq o custo das expenses não está ligado diretametne a centro de custo
* Renomear somente para `fetchTotalCost`

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchTotalCost/fetchMovementsTotalCost/index.ts
* Faz mais sentido ficar em `src/services/api/movements` pq o custo das expenses não está ligado diretametne a centro de custo
* Renomear somente para `fetchTotalCost`
* A rota na verdade é `/movements/total-value`

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchTotalCost/type.ts
Colocar essa tipagem em `src/commons/types`, afinal ela vai ser uma padronização das respostas de contadores

2023-09-20 16:59 UTC, ivanguimam commented on src/services/api/costCenter/fetchTotalCost/mock.ts
Criar um mock desse para atividades/expenses/movements, só para facilitar o uso mesmo

2023-09-21 12:14 UTC, ivanguimam requested changes

2023-09-21 12:32 UTC, deyvison-costa commented on src/components/ActivitiesDrawer/index.tsx
>      if (resourceType && resourceId) {
O que exatamente precisa estar nos filters é  "previousOpen" e "fetchActivitiesData" ou só  "previousOpen" ?

2023-09-21 13:48 UTC, ivanguimam approved these changes

2023-09-21 13:48 UTC, merged